### PR TITLE
Bootstrap RFCs and add initial RFC

### PR DESCRIPTION
**Pull request by maxammann**
This adds the RFC template and the initial RFC about RFCs.

Please comment.

Currently in draf mode because I just copy pasted a lot.

Upcoming RFCs will be:
* Input system
* Event loop
* Energy Saving
* 3D Projection
* Web(GL) support
* iOS support
* Android support
* Windows support
* Linux support
* Android SDK support
* iOS SDK support
* Qt support
* maplibre-gl-native interop
* headless rendering
* Tile fetching
* Tile tesselation
* Renderer architecture
* Styles Language & Architecture
* MapBox Styles
* Font rendering

### CODE REVIEW

**Review by nyurik — DISMISSED** [review]
absolutely love it!!!  Thank you for all the hard work!

**Comment by maxammann** [comment]
Haha thank you but this is copy&paste + search&replace 😃

Glad you like it! So it probably does not need much changes.

**Comment by nyurik** [comment]
@maxammann I'm not familiar with the RFC bootstrapping process itself - are you saying this PR should be cloned somehow?  Seems weird but i guess it is doable?

**Comment by maxammann** [comment]
> @maxammann I'm not familiar with the RFC bootstrapping process itself - are you saying this PR should be cloned somehow? Seems weird but i guess it is doable?

I'm just saying that the content was not written by me, but only adjusted. I gave now proper attribution :)

**Pull request merged**
