### PR TITLE
Chore: upgrade deps

### PR DESCRIPTION
**Pull request by nyurik**
* rename `keywords` into `categories` (because that's what it was used for), and added a new `keywords`
* bump nightly and stable rust versions
* run `just fmt`
* remove backends config for wgpu (dep no longer uses that param)

### CODE REVIEW

**Review by birkskyum — CHANGES_REQUESTED** [review]
Tests appear to be failing.

**Comment by maxammann** [comment]
Thanks! I was about to do the same as Eurorust prep.

I think rust must be updated

**Comment by nyurik** [comment]
@maxammann and/or @birkskyum  plz take a look

**Comment by maxammann** [comment]
Finally formatting for let else :)

**Review by maxammann — APPROVED** [review]

**Pull request merged**
